### ISSUE TITLE
Synchronizing "crashes" my internet connection

### ISSUE THREAD

**Issue by wulfihm** [clemahieu/raiblocks#404] opened 2018-01-05 12:22 UTC
Version 9.0
Windows 10

When synchronizing with the wallet websites are not reachable and generally the internet connection from the router is "crashed". When closing the rai wallet everything goes back to normal in <1min.

I think this problem is related to the number of pings per second. I had a similar problem with the steam server browser and reducing the amount of pings per minute to max. 500 solved the issue with that.

Someone told me that my router is at fault as it only can handle a set amount of pings per minute.

**Comment by wulfihm** [comment] 2018-01-05 16:24
Disabling "IP Flood Detection" setting in my router seems to have been fixing the problem.
I don't think I should have to do this for it to work but I am not sure.
Will leave this ticket open so someone can decide if there's something that should be done.

**Comment by androm3da** [comment] 2018-01-06 21:00
Thanks this is helpful, I've added it to the troubleshooting guide.

But I'll close this issue because it's this way by design.  I'll track this under #419

**Closed by androm3da** 2018-01-06 21:00 UTC
