### ISSUE TITLE
Segfault in latest trunk, block_store representation_add

### ISSUE THREAD

**Issue by hank** [clemahieu/raiblocks#602] opened 2018-02-11 04:21 UTC
**Description of bug:**
Segfault somewhere in the representative code.

**Steps to reproduce the issue:**
1. Compile and run
2. Wait for sync to occur for a while
3. Observe segfault

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:

- OS information 
- (Linux) Kernel (e.g. `uname -a`): Linux nyu 4.4.0-91-generic #114-Ubuntu SMP Tue Aug 8 11:56:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Node version: latest trunk (10..0) 22c647f2e59c2d3caf7c21e05e856386f62568b7

```
Core was generated by `/opt/raiblocks/rai_node --daemon'.
Program terminated with signal SIGSEGV, Segmentation fault.
---Type <return> to continue, or q <return> to quit---
#0  0x00000000006de930 in rai::block_store::representation_add(MDB_txn*, rai::uint256_union const&, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<128u, 128u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>, (boost::multiprecision::expression_template_option)0> const&) ()
[Current thread is 1 (Thread 0x7f44d0986700 (LWP 20104))]
(gdb) bt
#0  0x00000000006de930 in rai::block_store::representation_add(MDB_txn*, rai::uint256_union const&, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<128u, 128u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>, (boost::multiprecision::expression_template_option)0> const&) ()
#1  0x00000000006e42b6 in (anonymous namespace)::ledger_processor::change_block(rai::change_block const&) ()
#2  0x00000000006da479 in rai::ledger::process(MDB_txn*, rai::block const&) ()
#3  0x00000000005e65de in rai::block_processor::process_receive_one(MDB_txn*, std::shared_ptr<rai::block>) ()
#4  0x00000000005e832c in rai::block_processor::process_receive_many(std::deque<rai::block_processor_item, std::allocator<rai::block_processor_item> >&) ()
#5  0x00000000005e9bb5 in rai::block_processor::process_blocks() ()
#6  0x00000000008eac30 in execute_native_thread_routine ()
#7  0x00007f44d64d86ba in start_thread (arg=0x7f44d0986700) at pthread_create.c:333
#8  0x00007f44d5cf03dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by PlasmaPower** [comment] 2018-02-11 04:37
Duplicate of #598

**Closed** 2018-02-11 06:17 UTC

**Comment by paulmelis** [comment] 2018-02-11 13:45
I'm still seeing this issue, even with #603 merged. This is on Arch Linux (Linux llt0022 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux), source hash c42d669769692ddacfca38ef4d5153b8d94de1b4

```
0x0000555555892be3 in rai::block_store::representation_add(MDB_txn*, rai::uint256_union const&, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<128u, 128u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>, (boost::multiprecision::expression_template_option)0> const&) ()
(gdb) bt
#0  0x0000555555892be3 in rai::block_store::representation_add(MDB_txn*, rai::uint256_union const&, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<128u, 128u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>, (boost::multiprecision::expression_template_option)0> const&) ()
#1  0x00005555558950cc in (anonymous namespace)::ledger_processor::change_block(rai::change_block const&) ()
#2  0x000055555588f0c9 in rai::ledger::process(MDB_txn*, rai::block const&) ()
#3  0x00005555557b11a6 in rai::block_processor::process_receive_one(MDB_txn*, std::shared_ptr<rai::block>) ()
#4  0x00005555557b2f7e in rai::block_processor::process_receive_many(std::deque<rai::block_processor_item, std::allocator<rai::block_processor_item> >&) ()
#5  0x00005555557b44e7 in rai::block_processor::process_blocks() ()
#6  0x0000555555af9b9f in execute_native_thread_routine ()
#7  0x00007ffff736808c in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5c8ae7f in clone () at /usr/lib/libc.so.6
```

**Comment by cryptocode** [comment] 2018-02-11 14:55
@paulmelis you might need https://github.com/clemahieu/raiblocks/pull/604 as well

**Comment by paulmelis** [comment] 2018-02-11 16:43
Right, applying #604 as well seems to help

**Comment by PlasmaPower** [comment] 2018-02-11 20:14
#604 has been merged. This should now be fixed.

**Comment by paulmelis** [comment] 2018-02-16 09:19
Seems the hash2 stuff was reverted and this segfault is back

**Comment by paulmelis** [comment] 2018-02-16 10:46
Hmm, just noticed the remark in the v10 release notes about re-initializing the DB, might have something to do with this. Doing a fresh sync right now, will keep an eye on it.
