### ISSUE TITLE
Is it possible to cancel a transaction?

### ISSUE THREAD

**Issue by kapsi1** [clemahieu/raiblocks#382] opened 2018-01-03 12:09 UTC
I have a transaction stuck in pending. Is it possible to cancel it?

**Comment by AyiSoli** [comment] 2018-01-03 13:56
No pending means it just has to be received, it is final

**Comment by ryanjms07** [comment] 2018-01-04 11:28
It is not fair if the transaction is final, there must be cronjob to check transaction pending more than 4 days for example. cronjob will find transaction more than 4 days pending. if there is pending transaction more than 4 days, the coins will return to wallet sender. I think this is critical issue and must be add this feature for the future if raiblocks system will become good system.

**Comment by chpio** [comment] 2018-01-04 15:09
@ryanjms07
What's not fair? a "pending" TX *is* final

**Comment by ryanjms07** [comment] 2018-01-05 00:02
in the bank there is not pending more than 4 days (for example).
if tx pending for more 4 days, is it fair? you can imagine if you send the money and pending for 4 days, that send to your son for paid something important.
for example in the fact, bitgrail has change deposit address to change the rules, how about the people have sent some xrb below 100 xrb to bitgrail old deposit address before they change to new address deposit? it will pending forever. it is nonsense. it's the same as throwing away the xrb into the cloud and never landing forever.

**Comment by 5k1ttl3** [comment] 2018-01-05 07:40
@ryanjms07 

> it's the same as throwing away the xrb into the cloud and never landing forever.

Its not. Perhaps we need to work on some verbiage in the client, but once you sign and broadcast a transaction its gone forever. Its irrevocable. That's kind of the whole idea. 

If the other party wants to be gracious and send the mistaken transaction back to you, they certianly can.

Pending doesn't mean "lost in the ether, bouncing around forever never to be claimed" It means you've successfully sent it, and the recipient is free to claim it or not (The desktop client claims these transactions automatically). It's theirs to do with what they want.


If bitgrail is doing shady things, changing around addresses, and refusing to credit your accounts, that's a bitgrail problem unfortunately. I'd reach out to their support and ask them nicely to credit your account with whatever you feel is due to you. If that fails, then lesson learned. Spread the word about your interaction with them to reddit, twitter, etc.

**Comment by ryanjms07** [comment] 2018-01-05 10:33
in the case that you are talking about may be true.  
`bounces around forever never to be claimed. It means you've successfully sent it, and the recipient is free to claim it or not` 
how if the recipient never claim it as I spoke before (how about the people have sent some xrb below 100 xrb to bitgrail old deposit address before bitgrail change to new address deposit) ? it same as throwing xrb into the cloud and become a dust.

There are many people in telegram talk about pending deposit xrb in other account such as bitgrail and also my xrb deposit pending. because of it i request to add cronjob, if that's impossible, no problem. 
i have asking to admin bitgrail in telegram not response and also twitter still no response.

**Comment by chpio** [comment] 2018-01-05 11:02
"how if the recipient never claim it as I spoke before"
No, not that discussion again about deleting/"socializing" not moving coins.

What's if im at a vacation for a fee weeks and can't get online to receive TXes? Does it mean all the funds i got transferred to my account at the begging of the vacation get canceled after a fee days?

What's if i see and confirm a TX on a view only device, without the ability to change (and generate the receiving TX) the blockchain, then hand out a commodity im selling to never get access to the funds, because the TX got cancelled?

**Comment by androm3da** [comment] 2018-01-07 06:47
@ kapsi1 it's a great question but it gets at a core difference between the design of raiblocks and other coins.  This behavior is by design.

"Pocketing" a transaction moves it from "pending" to "received".  This operation could logically be considered the first required step of spending instead of the last step of receiving a spend.  A send is irreversible.

**Closed by androm3da** 2018-01-07 06:47 UTC
Labels: question

**Comment by pixelsage** [comment] 2018-01-21 23:06
@kapsi1 - Where did you see this "pending" transaction? You have a valid point, that from a user perspective, uncollected money looks like it's in "limbo." If anything, money shouldn't ever be considered "pending," but "sent."

**Comment by lamhonghuyen** [comment] 2018-12-04 20:01
I am researching Nano. The idea of setted & unsetted transaction is brilliance.
Believe me or not, the problem of sending fund to the wrong account is so common that almost happen to everybody I know. In the crypto currencies world you have no one to support if it happens. For the end-users, security is as important same as usability, if everytime users have worry about clicking the send button, I am sure no one will use cryptos instead of Credit Cards (which they have someone to back them up). I believe allowing sender to reclaim unsetted transaction in a particular time frames (e.g first some minutes no one claims the fund, and when the transaction expires) will bring Nano to the next level of adoption!

**Comment by renesq** [comment] 2019-05-06 06:05
Coranos developed a cryptographical procedure called "camo" to allow recipients and senders to opt-in to reversible transactions by creating child public keys and have a shared secret for those.

**Comment by ilius** [comment] 2019-05-06 08:12
Nano is fee-less and super fast
People should send a small amount like 0.001 NANO first, specially to new addresses / individuals, and wait for confirmation. Then send the rest. Unless they are quite certain about destination and amount.

**Comment by ilius** [comment] 2019-05-06 08:26
I'm not sure reversible transactions are even possible without a universally trusted entity (like people trust banks). Which is against the philosophy of both Bitcoin and Nano (and other community-based coins)
Even with Ethereum or other coins with smart contracts, a company needs to observe and supervise the network I think. Kind of similar to banks, but with less power.
